# Generated by Django 4.1.3 on 2022-11-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediants_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='ingrediant_list',
            field=models.ManyToManyField(to='menu.ingrediants'),
        ),
    ]
